export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL = 'FETCH_GAMES_FAIL';
export const LOADING_DETAIL = 'LOADING_DETAIL';
export const GET_DETAIL = 'GET_DETAIL';
export const LOADING_SEARCHED = 'LOADING_SEARCHED';
export const FETCH_DETAILS_FAIL = 'FETCH_DETAILS_FAIL';
export const FETCH_SEARCHED = 'FETCH_SEARCHED';
export const CLEAR_SEARCHED = 'CLEAR_SEARCHED';
