export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL = 'FETCH_GAMES_FAIL';
export const FETCH_SEARCHED = 'FETCH_SEARCHED';
export const CLEAR_SEARCHED = 'CLEAR_SEARCHED';
